### ISSUE TITLE
Operators and parameterized modules

### ISSUE THREAD

**Issue by robinheghan** [gren-lang/compiler#198]
One of the consequences of parameterized modules (#81) is that we'll move away from builtin "type classes" like `number` and `appendable`. This in turn means we need to find a solution for the current operators in the language, most of which rely on these builtin type classes.

We could:

1. Introduce new sets of operators that are type specific. `Int` can be covered by the existing math operators: `+`, `-`, `/`... `Float` can get dot-suffixed versions of those: `+.`, `-.`, `/.`... `++` might be changed to only work on Strings.
2. Remove all operators, functions all the way (unlikely).
3. Define operators in term of a parameterized module.

This proposal will explore option 3.

## Operators as parameterized modules

I'm going to start off with an example. Here's how the math operators can be specialized to a specific type:

```gren
module Example exposing (double)

import MathOps(Int) exposing ((+))

double : Int -> Int
double num =
  num + num 
```

We import the `+` operator from `MathOps`, which requires an input module to know which underlying implementation to use.

`MathOps` will be implemented as:

```gren
module MathOps exposing ( (+), (-), (*), (/) )

requires Number as N

infix left  6 (+) = N.plus
infix left  6 (-) = N.subtract
infix left  7 (*) = N.multiply
infix left  7 (/) = N.divide
```

Where `Number` is the signature required to instantiate `MathOps`, it will look something like:

```gren
module signature Number

type alias T

plus : T -> T -> T

subtract : T -> T -> T

multiply : T -> T -> T

divide : T -> T -> T
```

As long as a module implements the signatures defined in `Number`, it can be used with the math operators.

## Default imports

Most operators are currently included in Gren's default imports. This becomes problematic when we want users to be able to decide what the operators should work on.

One _could_ add a keyword that would "unimport" a module. But this seems a bit much when it would only ever be used for the default imported modules.

Another, more explicit way, would be to simply remove default imports altogether.

If so, the compiler would probably add a command for creating a new module, which would include the module name and a set of common imports, like: `gren generate Some.New.Module`

## Allowing function-scoped imports

One limitation of the current proposal is that operators would be bound to one type for the entire module. In the example at the top of this proposal, if you wanted to do some `Float` math, you would have to do it using regular functions, because the operators would be specialized to the `Int` type.

One way to work around this would be to allow import statements within function definitions, like so:

```gren
module Example exposing (double, doubleF)

import MathOps(Int) exposing ((+))

double : Int -> Int -> Int
double num =
  num + num

doubleF : Float -> Float -> Float
doubleF num =
  import MathOps(Float) exposing ((+))
  num + num
```

This would also require shadowing, in the context of module imports, to be ok.

**Comment by allanderek** [comment]
One consequence, and I'm being careful not to label it a positive or negative one, of using parameterised modules rather than type-classes for this kind of polymorphism (whether for operators or not), is that you're forced to lift the polymorphism to the module level.

So suppose you have a `List` module. You decide that you wish to add a `sum` function. You have two options:
1. You can accept the `add` as a function to the `sum` function.
2. You have to make the whole `List` module parameterised by something that implements `+`.
Note that in 2, you're basically just moving the the `add` function parameter from the `sum` function, to the module.

Note, also, that if you choose 2, you're making any callers of that `List.sum` function, which wish to leave themselves parametric in the type of elements and the `+` function, they sort of need to do it at the module level as well. To make it more concrete, suppose I'm implementing some datatype, that includes a list of things as part of its main type:

```
module A exposing ( gather )

type alias T a =
    { ... element : List a, ...  }

gather : (a -> a -> b) -> T a -> b
gather add input =
      -- Somewhere here I'd like to call
      List.sum add input.elements
```

Now the problem is, that the `List` module has instead used option 2 to parameterise the `List.sum` function, so I have to instead make module `A` also parameterised by the `add` functionality, or do something like:

```
gather : (a -> a -> b) -> B a -> b
gather add =
      -- Assume I have some syntax for local modules:
      module X = begin (+) = add .. end
      module L = List (X)
          L.sum x
```
Note here I've only given `(+)` in the module `X` but actually I'd have to satisfy the `Number` signature, unless of course you wrote a specific signature for the module that parameterises the `List` module, that only includes the `+` symbol. 

All-in-all, I'm not against parameterised modules, but I'm not sure this kind of polymorphism in their best use.
