### ISSUE TITLE
Support dependencies that reside on the local filesystem

### ISSUE THREAD

**Issue by robinheghan** [gren-lang/compiler#77]
It would be nice to be able to define dependencies that lives on the local filesystem. This would make it easier to test out unpublished packages, or for defining a package containing tests.

It's kinda possible to do this today by adding a folder to `source-directories`, however this comes with a few drawbacks:

* exposed-modules is not respected
* the dependencies are not respected
* projects of type `package` do not allow setting `source-directories`.

I therefore propose that you can add a project which resides on the local filesystem as a dependency, which for all intents and purposes work like any other dependency _except_ it is not pulled from a remote git repo.

Such packages should have a few restrictions

* you cannot publish a package which has a dependency on a local package
* local packages cannot contain kernel code, even if the name of the package starts with `gren/`.

In addition:

* projects with type `package` should gain the ability to define `source-directories`
* `test-dependencies` can be removed. Unit tests can be defined in a package which define the main project as a local dependency.

**Comment by allanderek** [comment]
Just to add that I believe this would much simplify contributing to an existing package. I recently had a simple two character fix that I wanted to apply to a published Elm package. It was simply a string literal that was slightly wrong. However I add to:
1. Clone the repo to my local file system
2. Add the repo's directory to 'source-directories' of the project I was using the package from
3. Compile and get an error because the package depends on things which the project'= does not, of course they are in the 'in-direct' dependencies of the project, but they need to be in the 'direct-dependencies'. At least it's just a move in the elm.json.
4. Repeat step 3 until I get all of the dependencies
5. Make the change I actually want to make in the package's repo
6. Make sure that now works for me in the project that uses the package
7. When the package is published with my fix included I basically need to reverse all these steps

Steps 3 (and 4) and 7 are the main friction. If I understand correctly this proposal would make steps 3, 4 and 7, one line changes.

This is basically also true if you're just beta-testing a package for someone before they publish it.

**Comment by robinheghan** [comment]
Implemented on main branch
